### ISSUE TITLE
Include configuration via the Authorino API for the new authorino log level env variable

### ISSUE THREAD

**Issue by jjaferson** [Kuadrant/authorino-operator#2]
Authorino has included support for different levels of logs, this can be defined via the `LOG_LEVEL` and `LOG_MODE` env vars. This issue is to enable the authorino operator to set these envs via the Authorino API in the spec block of the Authorino CR

```
apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
spec:
  logLevel: info
  logMode: production
  ...
```

https://github.com/Kuadrant/authorino/blob/main/main.go#L53-L54
