### ISSUE TITLE
Install plan is not getting generated when installing through Catalog Source

### ISSUE THREAD

**Issue by R3hankhan123** [Kuadrant/authorino-operator#211]
When trying to install the authorino operator through the catalog source using the following commands

`kubectl create namespace authorino-operator`

```
kubectl -n authorino-operator apply -f -<<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: authorino-operator
spec:
  sourceType: grpc
  image: quay.io/kuadrant/authorino-operator-catalog:latest
  displayName: Authorino Operator
EOF

kubectl apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: authorino-operator
spec:
  channel: alpha
  name: authorino-operator
  source: operatorhubio-catalog
  sourceNamespace: authorino-operator
  installPlanApproval: Automatic
EOF
```
The install plan is not getting generated and all available catalogsources are healthy

<img width="1437" alt="Screenshot 2024-09-17 at 2 55 42 PM" src="https://github.com/user-attachments/assets/cb920d56-a35a-4cf0-8670-1ae1795a8b3d">
<img width="1465" alt="Screenshot 2024-09-17 at 2 56 07 PM" src="https://github.com/user-attachments/assets/a1472586-b4c7-49d3-999f-9e4e3fd87329">
